### PR TITLE
Move iOS specific files to iOS folder

### PR DESCRIPTION
**Pull request by berkcaputcu**
Move all iOS related code into an iOS folder within the project

This checks off the first checklist item in #1

@jordanbyron

### CODE REVIEW

**Comment by jordanbyron** [comment]
@berkcaputcu thanks for the PR. Looks like this commit also includes a react-native version bump. Can you pull that out so we keep our commits atomic? Also can you include another commit with an update to the README's instructions to account for the new `iOS` folder?

Thanks again!

**Comment by berkcaputcu** [comment]
> Looks like this commit also includes a react-native version bump

I'll revert that. I don't think that needs to be in this PR.

**Comment by berkcaputcu** [comment]
@jordanbyron updated the PR. Can you take another look please?

**Comment by jordanbyron** [comment]
@berkcaputcu looks good to me. Thanks! :ship:

**Pull request merged**
